"use strict";
exports.__esModule = true;
var library_1 = require("./library");
var book_1 = require("./book");
var b1 = new book_1.Book("Harry Potter 1", 500, "EDS345", "Alguna", "JK Rowling");
var b2 = new book_1.Book("Harry Potter 2", 500, "EDS345", "Alguna", "JK Rowling");
var b3 = new book_1.Book("Harry Potter 3", 500, "EDS345", "Alguna", "JK Rowling 2");
var lib = new library_1.Library([b1, b2, b3], "Calles 123", "Juan");
console.log(lib.toString());
console.log(lib.getNumberOfBooks());
console.log(lib.findByAuthor("JK Rowling"));
