"use strict";
exports.__esModule = true;
var vector_1 = require("./vector");
var v1 = new vector_1.Vector(10, 100);
var v2 = new vector_1.Vector(10, 100);
v1.print();
v2.print();
console.log(v1.add(v2));
console.log(v1.subs(v2));
console.log(v1.mult(v2));
console.log(v1.multNumber(10));
